version: '3'

services:

  app:
    build:
      context: ./node
    container_name: app
    hostname: app
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - node-network

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    networks:
      - node-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    hostname: mongo-express
    networks:
      - node-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  node-network:
    driver: bridge