version: '3'

services:

  app:
    build:
      context: ./node
    container_name: app
    hostname: app
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - node-network

networks:
  node-network:
    driver: bridge